sudo: required 

language: python
git:
  depth: 3
services:
  - docker

before_install:
  - docker build -t order-service .

install:
  - echo "install nothing!" 

script:
  - docker run --rm order-service npm test
