sudo: required 

language: python
git:
  depth: 3
services:
  - docker

before_install:
  - touch .env
  - echo MONGO_HOST=$MONGO_HOST >> .env
  - echo MONGO_USERNAME=$MONGO_USERNAME >> .env
  - echo MONGO_PASSWORD=$MONGO_PASSWORD >> .env
  - echo MONGO_DATABASE=$MONGO_DATABASE >> .env
  - docker build -t order-service .

install:
  - echo "install nothing!" 

script:
  - docker run --rm order-service npm test
  - docker --version
  - pip install awscli 
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --no-include-email --region ap-southeast-1) 
  - docker tag order-service:latest 249502522254.dkr.ecr.ap-southeast-1.amazonaws.com/playground-order-service:latest
  - docker push 249502522254.dkr.ecr.ap-southeast-1.amazonaws.com/playground-order-service:latest
