sudo: required 

language: python
git:
  depth: 3
services:
  - docker

before_install:
  - docker build -t order-service .

install:
  - echo "install nothing!" 

script:
  - docker run --rm -e MONGO_CONNECTION_URL=$MONGO_CONNECTION_URL -e MONGO_HOST=$MONGO_HOST -e MONGO_USERNAME=$MONGO_USERNAME -e MONGO_PASSWORD=$MONGO_PASSWORD -e MONGO_DATABASE=$MONGO_DATABASE order-service npm test
