sudo: required 

language: python
git:
  depth: 3
services:
  - docker

before_install:
  - touch .env
  - echo MONGO_CONNECTION_URL=$MONGO_CONNECTION_URL >> .env
  - echo MONGO_HOST=$MONGO_HOST >> .env
  - echo MONGO_USERNAME=$MONGO_USERNAME >> .env
  - echo MONGO_PASSWORD=$MONGO_PASSWORD >> .env
  - echo MONGO_DATABASE=$MONGO_DATABASE >> .env
  - docker build -t order-service .

install:
  - echo "install nothing!" 

script:
  - docker run --rm order-service npm test
